# -*- coding: utf-8 -*-
"""
@author: Alejandro Ben 
"""

id_dict = {
    
    1: 'Aldazabal y Cía. S.A.',
    2: 'S.B.S Trading S.A.',
    5: 'Álvarez y Compañía Actividades Bursátiles S.A.',
    6: 'Allaria S.A.',
    7: 'Nacion Bursátil S.A.',
    8: 'Portfolio Investment S.A.',
    9: 'Banco Credicoop Cooperativo Limitado',
    11: 'Estructuras Financieras Regionales S.A.',
    12: 'Buenos Aires Valores S.A.',
    13: 'Bacqué S.A.',
    14: 'Banco de Servicios y Transacciones S.A.',
    15: 'Debursa ALyC S.A.',
    16: 'Mundo Bursátil S.A.',
    17: 'Banco Mariva S.A.',
    18: 'Cucchiara y Cía. S.A.',
    19: 'Bagnardi y Cía. S.A.',
    20: 'Proficio Investment S.A.',
    21: 'Confidas Capital S.A.',
    22: 'GMA Capital S.A.',
    23: 'Provincia Bursátil S.A.',
    24: 'Corsiglia y Cía. S.A.',
    25: 'Banco VOII S.A.',
    26: 'Becerra Bursátil S.A.',
    27: 'Lares Capital S.A.',
    28: 'Compañía de Inversiones Bursátiles S.A.',
    29: 'Banco Industrial S.A.',
    30: 'Liebre Capital S.A.U.',
    31: 'Aurum Valores S.A.',
    32: 'Nuevo Chaco Bursátil S.A.',
    33: 'Macro Securities S.A.U.',
    34: 'Banco de Comercio S.A.',
    35: 'Latin Securities S.A.',
    36: 'Arata S.A.',
    37: 'Argentina Valores S.A.',
    38: 'Capital Markets Argentina S.A.',
    39: 'ALYNK S.A.',
    40: 'Puente Hnos. S.A.',
    41: 'SJB S.A.',
    42: 'Banco de San Juan S.A.',
    43: 'Banco Supervielle S.A.',
    44: 'Banco BBVA Argentina S.A.',
    45: 'Dracma S.A.',
    46: 'Cohen S.A.',
    47: 'Banco del Chubut S.A.',
    48: 'Patagonia Valores S.A.',
    49: 'Benedit Bursátil S.A.',
    51: 'Grupo del Plata S.A.',
    52: 'Banco Comafi S.A.',
    53: 'Burplaza S.A.',
    54: 'Abut S.A.',
    55: 'Tarallo S.A.',
    56: 'Banco de la Provincia de Buenos Aires',
    57: 'Roagro S.A.',
    59: 'Global Valores S.A.',
    60: 'Baires Bursátil',
    61: 'Domínguez Tziavaras S.A.',
    62: 'Nasini S.A.',
    63: 'Dellepiane y Cía. S.C.',
    65: 'Option Securities S.A.',
    66: 'Five Corporation S.A.',
    67: 'LBO S.A.',
    68: 'Bahía Blanca Sociedad de Bolsa S.A.U.',
    69: 'Fernández Soljan S.A. (Suspendido preventivamente por CNV)',
    70: 'Banco de Valores S.A.',
    71: 'Agrosafe S.R.L.',
    73: 'Fernández Laya S.A.',
    74: 'ACA Valores S.A.',
    75: 'Falabella y Corsi Inversora S.A.',
    76: 'Giannoni S.A.',
    77: 'BTU Valores S.A.',
    78: 'Cano Bursátil S.A.',
    79: 'Mateo y Marchioni S.B. Agente de Mercado S.A.',
    80: 'Metrocorp Valores S.A.',
    81: 'Tomar Inversiones S.A.',
    82: 'TPCG Valores S.A.U.',
    83: 'Maxinta Valores S.A.',
    84: 'Fescina y Cía. S.A.',
    85: 'Mediterránea Valores y Acciones S.A.',
    86: 'Inviu S.A.U.',
    87: 'RL Valores S.A.',
    88: 'Bell Investments S.A.',
    89: 'Parakeet Capital S.A.',
    90: 'BT Securities Argentina S.A.',
    91: 'RIG Valores S.A.',
    92: 'Novillo Saravia y Cía S.A.',
    95: 'Zofingen Securities S.A.',
    96: 'Número Bursátil S.A.-Esp',
    97: 'ADCAP Securities Argentina S.A.',
    98: 'Valfinsa Bursátil S.A.',
    99: 'Banco de Corrientes S.A.',
    100: 'Comafi Bursátil S.A.',
    101: 'Petrini Valores S.A.',
    102: 'FX CAPITAL S.R.L.',
    104: 'Banco de la Nación Argentina',
    105: 'S&C Inversiones S.A.',
    106: 'GMC Valores S.A.',
    107: 'Intercapital S.A.',
    108: 'Nuevo Banco de Entre Ríos S.A.',
    109: 'Mariva Bursátil S.A.',
    110: 'R. Mackintosh S. A.',
    111: 'Lynx Valores S.A.',
    112: 'Nuevo Banco de Santa Fé S.A.',
    113: 'Alchemy Valores S.A.',
    114: 'Rosario Valores S.A.',
    116: 'Seguí y Cía. S.A.',
    118: 'WIN SECURITIES S.A.',
    119: 'REM Bursátil S.A.',
    120: 'Max Capital S.A.',
    121: 'Montelatici y Cía. S.A.',
    122: 'Industrial Valores S.A.',
    124: 'Macchi Valores S.A.',
    125: 'Bolsa de Comercio de La Plata',
    127: 'Maestro y Huerres S.A.',
    128: 'Navarro Viola y Cía. S.A.',
    129: 'Banco Santander Argentina S.A.',
    130: 'Valcereal S.A.',
    131: 'Banco de la Provincia de Córdoba S.A.',
    132: 'Arpenta Valores S.A.',
    133: 'Industrial and Commercial Bank of China (Argentina) S.A.U.',
    134: 'AG Valores S.A.',
    135: 'HSBC Bank Argentina S.A.',
    137: 'Mar Del Plata Bursátil',
    138: 'Reba Compañía Financiera S.A.',
    139: 'Banco Hipotecario S.A.',
    140: 'Mills Capital Markets S.A.',
    141: 'Rabello y Cía. S.A.',
    142: 'Neix S.A.',
    143: 'Deal S.A.',
    144: 'Aeromar Valores S.A.',
    145: 'Banco Meridian S.A.',
    146: 'INTAGRO S.A.',
    147: 'Fiorito Factoring S.A.',
    149: 'Banco de la Pampa S.E.M.',
    151: 'Invertir Online S.A.U.',
    152: 'Santander Valores S.A.',
    153: 'Bolsa de Comercio del Chaco',
    154: 'Miguel J. Carril S.A.',
    155: 'Sociedad Militar Seguro de Vida Institución Mutualista',
    158: 'Los Tilos Bursátil S.A.',
    159: 'Cía. Gral. de Valores Mobiliarios S.A.',
    161: 'Ualintec Capital S.A.U.',
    162: 'BLD Finanzas S.A.',
    163: 'Prosecurities S.A.',
    164: 'DHALMORE CAPITAL S.A.',
    165: 'Tutelar Bursátil S.A.',
    166: 'Banco Bica S.A.',
    168: 'Dinosaurio Bursátil S.A.',
    169: 'Facimex Valores S.A.',
    170: 'Eco Valores S.A',
    171: 'BMA Valores S.A.',
    173: 'Napoli Inversiones S.A.',
    174: 'Banco de Formosa S.A.',
    175: 'Rey López Bursátil S.A.',
    176: 'Schweber Securities S.A.',
    177: 'Banco Itaú Argentina S.A.',
    178: 'Agencia de Liquidación y Compensación Córdoba S.A.',
    179: 'BACS Banco de Crédito y Securitización S.A.',
    180: 'Rava Bursátil S.A.',
    181: 'Ranallo Valores S.A.',
    182: 'PGA Valores S.A.',
    183: 'Integrar S.A.',
    184: 'Patente de Valores S.A.',
    186: 'Servente y Cía. S.A.',
    187: 'QUANT CAPITAL S.A.',
    189: 'Mario S. Fernandez y Cía S.A.',
    190: 'BACS Administradora de Activos S.A. Sociedad Gerente de Fondos Comunes de Inversión',
    191: 'Diaz Riganti Cereales S.A.',
    192: 'Compañía Global de Inversiones S.A.',
    194: 'Enrique R. Zeni y Cía. SACIAFeI',
    195: 'STC Inversiones S.A.',
    196: 'Eurovalores S.A.',
    197: 'Listro Valores S.A.',
    198: 'Rey Leyes Valores S.A.',
    199: 'Banco Macro S.A.',
    200: 'Bull Market Brokers S.A.',
    201: 'Alfy Inversiones S.A.',
    202: 'Transatlántica S.A. Bursátil',
    203: 'Invertir en Bolsa S.A.',
    204: 'Federal Bursátil S.A.',
    205: 'Tavelli y Cía. S.A.',
    206: 'Intervalores Group S.A.',
    207: 'Alycbur S.A.',
    208: 'Comercio Interior S.A.U.',
    209: 'Futuro Bursátil S.A.',
    210: 'BRIO Valores ALyC S.A.',
    211: 'Luis Domingo Trucco S. A.',
    212: 'Ubertone y Cía. S.A.',
    213: 'Rosental S.A.',
    214: 'Reconquista Valores S.A.',
    216: 'C.A. Teuly & Co. S.A.',
    217: 'Centaurus Securities S.A.',
    218: 'Venini Núñez S.A.',
    219: 'Banco de Galicia y Buenos Aires S.A.U.',
    220: 'Longo Elia Bursátil S.A.',
    222: 'Banco Julio S.A.',
    223: 'Bluelake Capital S.A.',
    225: 'GIO Bursátil S.A.',
    227: 'Cono Sur Inversiones S.A.',
    228: 'Banco de la Ciudad de Buenos Aires',
    229: 'CITIBANK N.A.',
    231: 'Guor Investments S.A.',
    232: 'Nix Valores S.A.',
    233: 'Sailing S.A.',
    234: 'Porzio Bursátil S.A.',
    235: 'Criteria WM S.A.',
    237: 'Brancatelli S.A.',
    238: 'Balanz Capital Valores S.A.U.',
    239: 'Bursátil Uspallata S.A.',
    240: 'STONEX Securities S.A.',
    241: 'Transacciones Agente de Valores S.A.',
    242: 'Morandi Valores S.A.',
    243: 'Banco Patagonia S.A.',
    244: 'Spread Inversiones S.A.',
    245: 'Euro Bursátil S.A.',
    246: 'Banco de Santa Cruz S.A',
    248: 'Finance S.A.',
    249: 'CABSA S.A.',
    251: 'GG INVERSIONES Y NEGOCIOS S.A.',
    253: 'Versátil Inversiones y Transacciones S.A.',
    254: 'SECURITIES CAF ARGENTINA S.A.',
    255: 'BIBANK S.A.',
    256: 'SZWARC & CIA. S.A.',
    257: 'LEIVA HERMANOS S.A',
    258: 'Banco de Inversión y Comercio Exterior S.A',
    259: 'Consultatio Investments S.A.',
    260: 'FINCO CAPITAL S.A.',
    261: 'Arpenta S.A.',
    262: 'PP Inversiones S.A.',
    263: 'Galicia Securities S.A.U.',
    264: 'Allaria Agrofinanzas S.A.',
    265: 'Cocos Capital SA-Esp',
    266: 'BTG Pactual Argentina S.A.U.',
    267: 'DMA Broker S.A.',
    268: 'Barrilli S.A.',
    269: 'JPMorgan Chase Bank NA (Suc. Bs. As.)',
    270: 'Banco CMF S.A.',
    271: 'AgroBrokers S.R.L.',
    272: 'Guarnieri Valores S.A.',
    273: 'Banco Piano S.A.',
    275: 'Laguna S.A.',
    277: 'Grassi S.A.',
    278: 'Stockbrokers S.A.',
    281: 'Futuros y Opciones.com S.A.',
    282: 'Dillon William S.R.L.',
    284: 'Veta Capital S.A.',
    285: 'DA Valores S.A.',
    287: 'ARG Securities Advisors S.A.',
    290: 'Columbus IB Valores S.A.',
    292: 'First Capital Markets S.A.',
    293: 'Múltiplo Bursátil S.A.',
    295: 'Inversiones Cuyanas S.A.',
    297: 'Don Capital S.A.',
    298: 'UG Valores S.A.',
    482: 'Enlace INTL S.A.',
    485: 'FES S.A.',
    486: 'DelSur Brokers S.A.',
    487: 'Tradition Argentina S.A.',
    489: 'BT Brokers S.A.',
    801: 'Vector Investments S.A.',
    802: 'Orion Capital S.A.',
    803: 'Coppola Inversiones S.A.',
    804: 'Meta Inversiones S.A.',
    805: 'Banco Coinag S.A.',
    806: 'SBT Valores S.A.',
    807: 'Gorostiaga Bursátil S.A.',
    808: 'Beta Group Inversiones S.A.',
    809: 'Regional Investment Consulting S.A.',
    810: 'Omega Bursátil S.A.',
    811: 'Real Market S.A.',
    812: 'Manta Compañía Inversora S.A.',
    813: 'DFC Capital Management S.A.',
    814: 'Inverstart S.A.',
    815: 'Industria Compañía Bursátil S.A.',
    816: 'Palm Inversiones S.A.',
    817: 'América Valores S.A.',
    818: 'Fernando Bibe e Hijos S.A. ',
    819: 'Hoss S.A.',
    820: 'AWA Global S.A.',
    821: 'Bamba Valores S.A.',
    822: 'Conectar Bursátil S.A.',
    823: 'Buenos Aires Créditos y Valores S.A.',
    824: 'Inverfin S.A.',
    825: 'Puertos S.R.L.',
    826: 'Supervielle Agente de Negociación S.A.U.',
    827: 'Bafomet S.A.',
    828: 'Elyca Servicios Globales S.A.',
    829: 'PSA La California S.A.',
    830: 'Global Market Valores S.A.',
    831: 'Cooperativas Agropecuarias Federadas de Entre Rios Coop. Ltd. (C.A.F.E.R.)',
    832: 'Zona Bursátil S.A.',
    833: 'Agroinversiones Pampeanas S.A.',

}